sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

before_script:

script:
  - npm test
  - ng build --prod --aot
  - npm run precache

after_success:
  - npm run coveralls

notifications:
  email:
    recipients: aerts.stefan@gmail.com
    on_success: change
    on_failure: always
